### ISSUE TITLE
couple of things for the readme

### ISSUE THREAD

**Issue by xahare** [rgl/proxmox-ve-cluster-vagrant#1]
plugin dependency, vagrant-reload

on libvirt, run vagrant up with --no-parallel, otherwise pve2 or 3 might try to join the non existent cluster and fail.

**Comment by rgl** [comment]
done at https://github.com/rgl/proxmox-ve-cluster-vagrant/commit/5c3d2a4d3a8505ba7cfaa02a94c5e29e154998f2
