### ISSUE TITLE
Breaking Changes PVE 6.1

### ISSUE THREAD

**Issue by majacal** [rgl/proxmox-ve-cluster-vagrant#2]
hi @rgl,

thanks for the nice pve-lab here. i tried it out but i have some trouble. i guess there are some breaking changes in pve 6.x so that the pvecm create command fail.

**can u reproduce it?**

```
PVE 6.x has a new parameter "link0" and "link1" (previously ring0/1_addr), bindnetX_addr is gone altogether. check the "pvecm" manpage or the admin guide: https://pve.proxmox.com/pve-docs/pve-admin-guide.html#_cluster_network
```

the provision failed with:

```
   pve1: + pvecm create example --ring0_addr 10.2.0.201 --bindnet0_addr 10.2.0.0
    pve1: Unknown option: ring0_addr
    pve1: Unknown option: bindnet0_addr
    pve1: 400 unable to parse option
    pve1: pvecm create <clustername> [OPTIONS]
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

kind regards
matthias

**Comment by rgl** [comment]
I'm sorry, I still haven't updated this repo, I'm now noticing that I have changes in my working directory that are still not published... I'll update once I have it working.

**Comment by rgl** [comment]
It should now work. Let me known how it goes.

**Comment by majacal** [comment]
@rgl thanks a lot i will check it and give u feedback!

**Comment by majacal** [comment]
hey @rgl ,

i have just tested it and it works fine without any error, i guess this issue can be closed 

thank u for your quick fix , this repo helps me a lot! :)

kind regards
matthias
