### ISSUE TITLE
cluster network

### ISSUE THREAD

**Issue by DrummyFloyd** [rgl/proxmox-ve-cluster-vagrant#9]
hi , thnak you for you project, it help me alot with Vagrnt NAT ... which is  real pain ...

but i may found an issue on your cluster address. (10.0.1.20x)

it seems , that all pvex can' communicate over the **10.0.1.20x** .
it's ok with all the other adresses

pve<>pve on 10.0.2.x no OK 
gateway<> pve 10.0.2.x not ok 

pve<>pve on 10.0.1.x  OK 
gateway<> pve 10.0.1.x  ok 

so i i use all configuration i can't create a custer..

any idea why ? 

thank you

**Comment by rgl** [comment]
Not sure what you mean, as here (running in a ubuntu libvirt host), everything is working as expected.

As I've tried to [illustrate in the diagram](https://github.com/rgl/proxmox-ve-cluster-vagrant/blob/master/cluster.png), this is what is supposed to happen:

The service network (10.0.1.0/24) is accessible by all pve nodes, pve workloads (vms and containers), and the gateway.

The cluster network (10.0.2.0/24) is only accessible by the pve nodes.

The storage network (10.0.3.0/24) is only accessible by the pve nodes.

**Comment by DrummyFloyd** [comment]
will try to be more specific ,

when i start the Vagrantfile i  have a TO, when the node try to connect to each other ( pve1,pve2,pve3)
so the cluster is not able to be created.

then when i tried to ping pve2 from pve1, like `vagrant ssh pve1 -c 'ping 10.0.2.202'`
i've got a error this


```
❯ vagrant ssh pve1 -c "ping 10.0.2.202"
==> vagrant: You have requested to enabled the experimental flag with the following features:
==> vagrant: 
==> vagrant: Features:  typed_triggers, disks
==> vagrant: 
==> vagrant: Please use with caution, as some of the features may not be fully
==> vagrant: functional yet.
PING 10.0.2.202 (10.0.2.202) 56(84) bytes of data.
From 10.0.2.15 icmp_seq=1 Destination Host Unreachable
From 10.0.2.15 icmp_seq=2 Destination Host Unreachable
From 10.0.2.15 icmp_seq=3 Destination Host Unreachable
```

any idea why ?

thank you for your response
NB: i may have to specify that i run ths on virtualbox

**Comment by rgl** [comment]
Ah, you are using VirtualBox. I now understand what you've originally written as "vagrant nat". It seems there's a network addressing conflict with the default virtual box nat network. It should be changed from 10.0.2.0/24 to something else (eg. 10.1.2.0/24) or you need to change this environment networks. 

As a general rule of thumb. All the network interfaces of a particular machine must be in different networks.

**Comment by DrummyFloyd** [comment]
thank @rgl  seems to work ! 
sorry to bother you with such a dumb question!

have a nice day 

maybe , i will add a request to fore the NAT adress for Vbox
